version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./fast_api_app/populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql

  app:
    # build: .
    # command: uvicorn fast_api_app.app:app --host 0.0.0.0 --port 8000 --reload
    image: j4ro123/fastapi-app:latest
    container_name: fastapi-app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      host: db
      database: ${database}
      user: ${user}
      password: ${password}
      port: 5432 # Inside the container, it will use the default PostgreSQL port

volumes:
  pgdata:
